---
title: "Original studies preprocessing"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
library(kableExtra)
theme_set(theme_bw())
library(ggrepel)
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../../helpers.R")

e1 <- read.csv("../data/exp1.csv", fill = TRUE)
e1["Version"] <- "Exp1"

e2 <- read.csv("../data/exp2.csv")
e2["Version"] <- "Exp2"

```


```{r}
# Convert all columns except ResponseID to character
e1[,-1] <- lapply(e1[,-1], as.character)
# e2[,-1] <- lapply(e2[,-1], as.character)

e1_long <- e1 %>%
  pivot_longer(
    cols = -ResponseID,           # All columns except 'ResponseID'
    names_to = "Question",        # Name for the new column containing former column names
    values_to = "Response"        # Name for the new column containing the data
  )


View(e2)
e2_long <- e2 %>%
  pivot_longer(
    cols = -ResponseID,           # All columns except 'ResponseID'
    names_to = "Question",        # Name for the new column containing former column names
    values_to = "Response"        # Name for the new column containing the data
  )
```


```{r}
View(e2)
```


