---
title: "Analysis"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../../helpers.R")
```

```{r}
d <- read.csv("../data/processed.csv")
d$LogRT <- log(d$RT)
names(d)
```

# convert everything to factors
```{r, include=FALSE, warning=FALSE, echo=FALSE}
str(d)

convert_except <- function(df, exclude_cols) {
  df[] <- lapply(names(df), function(col_name) {
    if (!(col_name %in% exclude_cols)) {
      return(as.factor(df[[col_name]]))  # Convert to factor if not in excluded columns
    } else {
      return(df[[col_name]])  # Leave the excluded columns unchanged
    }
  })
  return(df)
}
# Specify columns to exclude from conversion
exclude_columns <- c('RT', 'LogRT')

# Convert all columns to factors except for 'a' and 'd'
df_factors <- convert_except(d, exclude_columns)

# Check the structure of the modified data frame
str(df_factors)

```

```{r, include=FALSE, warning=FALSE, echo=FALSE}
contrasts(df_factors$ConcValCombo)
contrasts(df_factors$Task)

center = df_factors %>%
  mutate(cTask = as.numeric(Task)-mean(as.numeric(Task)),
         cAccuracy = as.numeric(Accuracy)-mean(as.numeric(Accuracy)))
  
  # droplevels()
```

# Is there a difference between Semantic and Valence Tasks?
Yes.

```{r}

m = lmer(LogRT ~ cTask + (1|ID.true) + (1+cTask|Word), data=center)
# saveRDS(m.ms.ma.full, "../models/model-task-para.rds")

# m <- readRDS("../models/m.rds")
summary(m)
```

# Is there an Interaction between Task and WordType (ConcValCombo)?
No.
```{r}

m = lmer(LogRT ~ cTask*ConcValCombo + (1+ConcValCombo|ID.true) + (1+cTask+ConcValCombo|Word), data=center)
# saveRDS(m.ms.ma.full, "../models/model-task-para.rds")

# m <- readRDS("../models/m.rds")
summary(m)
```


