---
title: "Exploring individual differences"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../../helpers.R")
```

```{r}
d <- read.csv("../data/processed.csv")
d$LogRT <- log(d$RT)
names(d)
```

# Goals

The goals of this analysis is to determine to what extent the differences we find hold within the sample of participants. 

The piloting results tell us that there are indeed task differences for RT.

To that end we can ask:

1. What percentage of the participants show this effect?

2. What percentage of items showed this effect?

# Differences by-item

```{r}
x
```




